# Generated by Django 4.1.7 on 2023-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_alter_departmentposition_positionlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentposition',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Position leveli'),
        ),
    ]
